version: '3.8'

services:
  fraudguard-backend:
    build: .
    container_name: fraudguard-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    working_dir: /app/backend
    command: python main.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  fraudguard-frontend:
    build: .
    container_name: fraudguard-frontend
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    working_dir: /app/frontend
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - fraudguard-backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: fraudguard-network
